name: Build executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  name: statusbar
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch: [x86, x64]
    runs-on: windows-lastest

    steps:
    - uses: actions/checkout@v3
    - name: Build x86
      if: ${{ matrix.arch == 'x86' }}
      run: |
        rustup target add i686-pc-windows-msvc
        cargo tauri build --verbose --target i686-pc-windows-msvc
    - name: Build x64
      if: ${{ matrix.arch == 'x64' }}
      run: cargo tauri build --verbose
    - name: Upload installer package
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ${{ env.PROCESSOR_ARCHITECTURE }} Package
        path: |
          ${{ github.workspace }}/src-tauri/target/release/bundle/msi
          ${{ github.workspace }}/src-tauri/target/release/${{ env.name }}.exe
